### PR TITLE
Bump gems and fix CI

### PR DESCRIPTION
**Pull request by greysteil**
Should all be non-breaking. Recommend [dependabot](https://dependabot.com) for doing this stuff automatically (disclosure: I built it!).

### CODE REVIEW

**Comment by greysteil** [comment]
CI failure here is because it's hanging on the `deployment` stage, but otherwise specs are passing. Will leave that one to you :)

**Comment by andreausu** [comment]
Thanks! I'm on vacation right now without a cheap internet connection, I'll merge it next week :)

**Comment by greysteil** [comment]
👍  - enjoy your vacation!

**Comment by andreausu** [comment]
Thanks!

**Comment by andreausu** [comment]
Merged, deployed and set up dependabot (great job btw!), thanks!

**Pull request merged**
